services:
  # Build static frontend to a shared volume (Nginx serves it)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: ["true"]   # build-only
    volumes:
      - frontend_static:/usr/share/nginx/html
  
  ollama:
    image: ollama/ollama:0.3.12
    restart: unless-stopped
    ports:
      - "11434:11434"
    environment:
      OLLAMA_MODEL: phi3:mini
    entrypoint: ["/bin/sh","-lc","ollama pull $${OLLAMA_MODEL} || true; exec ollama serve"]
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file: ./.env.local # change to env.prod in prod
    expose:
      - "8000"
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80" # change to 80:80 in prod (or applicable defined in security group); when running in prod add 443:443 for HTTPS
    volumes:
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - frontend_static:/usr/share/nginx/html:ro
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: appdb
    ports:
      - "5432:5432" # remove in prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d appdb"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s
  
  mailpit: # only used for dev testing; remove in prod
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    restart: unless-stopped
  

volumes:
  pgdata:
  frontend_static:
  ollama:
